FROM docker pull nickstenning/slapd

MAINTAINER Brian Vanderbusch <brian@hackerhappyhour.com>

ENV LDAP_DOMAIN hackerhappyhour.com

ENV LDAP_ORGANIZATION "Hacker Happy Hour"

ENV LDAP_ROOTPASS s3cr3tpassw0rd
